name: Products API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, zip, pdo, pdo_mysql
        coverage: xdebug

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --testdox

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/debian/PayeTonKawa-Products
          git pull origin main

          cd /home/debian/PayeTonKawa
          sudo docker-compose stop PTK-api-products
          sudo docker-compose up -d --build PTK-api-products

          sudo docker exec PTK-api-products cp .env.example .env
          sudo docker exec PTK-api-products sed -i 's/DB_HOST=127.0.0.1/DB_HOST=PTK-db-products/g' .env
          sudo docker exec PTK-api-products sed -i 's/DB_PASSWORD=/DB_PASSWORD=root/g' .env
          sudo docker exec PTK-api-products php artisan key:generate
          sudo docker exec PTK-api-products php artisan migrate --force

          echo "Products API deployed successfully!"
