name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Verify Nginx Configuration
      run: |
        echo "Validating Nginx configuration..."
        # Cette étape peut être enrichie avec une validation syntaxique si nécessaire
    
    - name: Deploy to Production
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/debian/payetonkawa/PayeTonKawa
          git pull origin main
          
          # Configuration Nginx
          if [ -f nginx-conf-fixed.txt ]; then
            sudo cp nginx-conf-fixed.txt /etc/nginx/sites-available/payetonkawa
            sudo nginx -t && sudo systemctl reload nginx
          fi
          
          # Redémarrage des conteneurs
          sudo docker-compose down
          sudo docker-compose up -d
          
          echo "Deployment completed successfully!" 