name: Deploy Products Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 51.77.137.241 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh debian@51.77.137.241 '
            cd /home/debian/payetonkawa/PayeTonKawa-Products &&
            rm -rf * &&
            git clone https://github.com/MSPR2-PayeTonKawa/PayeTonKawa-Products.git . &&
            git checkout main
          '

      - name: Restart services
        run: |
          ssh debian@51.77.137.241 'cd /home/debian/payetonkawa/PayeTonKawa && sudo docker-compose restart api-products'

      - name: Run migrations
        run: |
          ssh debian@51.77.137.241 'cd /home/debian/payetonkawa/PayeTonKawa && sudo docker-compose exec -T api-products php artisan migrate --force'
